### ISSUE TITLE
Support scp-like syntax for the SSH protocol

### ISSUE THREAD

**Issue by devmondo** [Orbs/jspm-git#15]
hi,

i have done this 
```
jspm endpoint create mygitlab jspm-git
```
 and config result is 
```
"mygitlab": {
      "timeouts": {
        "lookups": 60
      },
      "baseurl": "git@gitlab.com:code.bakery/",
      "reposuffix": ".git",
      "auth": "n1a3rtedgZZKDkghS5u7Swj",
      "shallowclone": true,
      "handler": "jspm-git"
    }
```

this gives me error
 Endpoint not found.

but if i change endpoint name to "gitlab"  it works

another thing is that with above i may have different account like code.backery, devmondo so if i set base url to "git@gitlab.com" it does not work, it must specifically add the account name as above

thanks in advanced.

**Comment by subesokun** [comment]
Hi @devmondo,

thank you very much for reporting this. As I don't have an account at gitlab.com I can't really test the configuration but I think something goes wrong internally when joining the baseurl with the repo name.

As a quick workaround you could test the following

```bash
git clone ssh://git@gitlab.com/code.bakery/reponame.git
```

If that works for you please set the baseurl of the endpoint to `ssh://git@gitlab.com` and then try installing your packages via `jspm install mygitlab:code.bakery/reponame` (without .git at the end)

As a general feedback I'd not recommend to add the account name (e.g. `code.bakery`) directly into the baseurl as otherwise you'll end up creating for every new account an extra jspm-git endpoint.

Furthermore I'd recommend that you delete once the mygitlab configuration in the `~/.jspm/config` file as your current endpoint config is now a mixture out of the jspm-github and jspm-git endpoint. After deleting it you can create this mygitlab endpoint from scratch again.

**Comment by devmondo** [comment]
thanks a lot mate for reply the ssh://git@gitlab.com worked fine and now i don't have to hard code user account, but still the name part is not working it has to be gitlab.

here is gitlab url format for any repo 
```
git@gitlab.com:code.bakery/maa.git
```
i think somewhere in your code you are hard coding the name and preppend it to the url, or it is jspm bug ?

**Comment by subesokun** [comment]
Which name part are you meaning explicitly? In the [git.js#L32](https://github.com/Orbs/jspm-git/blob/7da4d6aa81798f2d2818357533841d54a8d2ab8b/git.js#L32) you can see how the URL gets created.

**Comment by devmondo** [comment]
what i mean is this 
```
jspm endpoint create mygitlab jspm-git
```
this produces 
```
 "mygitlab": {
      "timeouts": {
        "lookups": 60
      },
      "baseurl": "ssh://git@gitlab.com",
      "handler": "jspm-git",
      "reposuffix": ".git",
      "shallowclone": true
    }
```

it does not work and i get this error
```
D:\Websites\Tests\skeleton-navigation>jspm install mygitlab:code.bakery/maa

err  Endpoint not found.

err  Unable to load endpoint gitlab

warn Installation changes not saved.
```
but if i do 
```
jspm endpoint create gitlab jspm-git
```
everything works fine

**Comment by subesokun** [comment]
Mh very stange. I've just tested it with jspm 0.14.0 and everything works as expected. Can you do a `jspm -v` and maybe also show me the content of your `D:\Websites\Tests\skeleton-navigation\config.js`?

**Comment by subesokun** [comment]
I think I can reproduce now your error. If you write e.g.
```
"dummygitlab:*": "jspm_packages/mygitlab/*.js"
```
in your `config.js` then calling `jspm install` will throw following error:

```bash
> jspm install mygitlab:....

err  Endpoint not found.

err  Unable to load endpoint dummygitlab

warn Installation changes not saved.
```

@guybedford Is it possible to make this error a bit more specific so that you can distinguish between a real missing endpoint or if something is off with the configuration?

**Comment by guybedford** [comment]
Does this help - https://github.com/jspm/jspm-cli/commit/d5c4b52d19fc77e58aa225d33717e6163f126cff?

**Comment by subesokun** [comment]
@guybedford Thank you for the quick fix! Yes I think that helps. Not sure if this kind of endpoint error happens often as it's only a corner case which you'll only see if you manually modify the `config.js` as mentioned obove.

@devmondo Regarding the baseurl issue, I'll fix the jspm-git URL handling so that it supports also `git@host.com:../..` formatted URLs.

**Comment by devmondo** [comment]
@subesokun  thank you :)

**Comment by subesokun** [comment]
@devmondo jspm-git v0.3.2 has been now released which includes the fix for `git@host.com:../..` formatted URLs. Have fun with it :)

**Comment by devmondo** [comment]
thank you mate :)
