### ISSUE TITLE
configuration for git repository in file system

### ISSUE THREAD

**Issue by maku** [Orbs/jspm-git#18]
I would like to use a simple git repository which is only available on a share network drive (on a windows machine).

It seems not possible to define the baseUrl with e.g. file:///myserver/d$/git_repo 
Is there a way to do this??

**Comment by subesokun** [comment]
Lets assume file:///some/path/repofolder is the path to your Git repo, try setting file:///some/path as baseuri and then run "jspm install myendp:repofolder". Sorry I can test it first on weekend.

**Comment by subesokun** [comment]
One more thing, the key point is that "git clone file:///..." must work so that it works also with jspm-git as it always tries to clone the repo at the moment. There is no check so far to detect if that repo is already locally cloned.

**Comment by subesokun** [comment]
@maku Actually it's working for me. You've to make sure that the baseURL is a valid URI according to RFC 3986. If the repo folder is located at e.g. `C:/Users/Subesokun/Documents/GitHub/my-sample-repo` this configuration worked for me
```bash
jspm registry create mygit jspm-git
# baseurl: file:///C:/Users/Subesokun/Documents/GitHub
# In case your repo folder has no .git ending:
#    Advanced config > repo suffix > empty = yes
```
```bash
jspm install mygit:my-sample-repo
```
As you said your repo is located on a shared network drive please make use that you use `file://myserver` instead of `file:///myserver` as the tripple `///` is a shortcut for `localhost`.

As jspm-git is looking for Git tags please make sure that this repo has valid tags to install from.

**Comment by subesokun** [comment]
I'm closing this issue for now but if you've further questions please feel free to ask.
