### ISSUE TITLE
How to configure and install jspm-git in bitbucket repository?

### ISSUE THREAD

**Issue by gokul11** [Orbs/jspm-git#43]
I am new in jspm and jspm-git. I followed the below steps to install the jspm package using jspm-git from bitbucket repository.

1. I already installed jspm and jspm-git globally in my machine.

2. I configured the below jspm options in my bitbucket repository's package.json.
```
"jspm": {
    "registry": "jspm",
    "name": "my-package",
    "registries": {      
      "bitbucket": {
        "baseurl": "git+ssh://git@bitbucket.org/",
        "handler": "jspm-git"
      }
    }
  }
```
3. I run the below command to install the above private bitbucket repository in a new application.

`jspm install bitbucket:my-accountname/my-reponame.git`

After running the above command I got the below error.

`err  Repo bitbucket:my-accountname/my-reponame.git not found!`

Can you please let me know how to configure and install a private bitbucket repository using jspm-git?

**Comment by subesokun** [comment]
Hi @gokull11, as jspm-git uses Git to clone your repository you could try if the following works for you

`git clone git+ssh://git@bitbucket.org/my-accountname/my-reponame.git`

If that works for you usually jspm-git should also work in case you've some valid semver tagged commit e.g. `v1.2.3`.

Otherwise you could try to configure jspm-git globally. Honestly I've never tried to store the registry configuration directly in the package.json.

`jspm registry create but bucket jspm-git`

**Comment by gokul11** [comment]
Thanks for the update subesokun. 

Where can I store the config settings in my project, config.js?

I have another doubt. If I have a dependency project which is also a private bitbucket repository of mine, then how to setup this to my current cloned project. 

I am very new to this repositories and package management, so I couldn't understand the jspm doc.

**Comment by gokul11** [comment]
Thanks @subesokun. I figured it out about how to configure.
