### ISSUE TITLE
ssh:// base URL with port broken

### ISSUE THREAD

**Issue by pasky** [Orbs/jspm-git#48]
If we specify base git url ssh://username@hostname:port/ (i.e. with a custom ssh port), git itself handles that just fine, but we are getting errors from jspm-git:

  Error: ssh: Could not resolve hostname HOSTNAME:PORT: nodename nor servname provider, or not known

Any idea what's going on? Thanks!

**Comment by subesokun** [comment]
Hi @pasky, in my environment I'm using also a custom port so generally there shouldn't be an issue. You said git itself works fine, could you confirm that once more with
```
git clone ssh://username@hostname:port/account/repo.git
```
Because jspm-git is actually running this command in a separate child process behind the scenes. Maybe you could show me also your jspm config (~/.jspm/config).

**Comment by pasky** [comment]
Yes, git clone worked just fine at that time.  But unfortunately I can't get access to the machine where we had this issue for other reasons now, it turns out, so if it's something that's supposed to work, I'll close this issue now, and reopen if we hit the problem again.  Sorry for the noise!
