### ISSUE TITLE
NPM dependencies in package.json attempted with myGit:<npm dependency name>

### ISSUE THREAD

**Issue by justinwilaby** [Orbs/jspm-git#49]
There seems to be a problem with installing npm dependencies that exist within the `package.json` of a project installed using this tool.  

`jspm install myGit:owner/project` fails with:

```
warn Error on lookup for myGit:rollup-plugin-babel
Error: fatal: /info/refs not valid: is this a git repository?
```

Where `rollup-plugin-babel` is an NPM dependency listed in the `package.json` of the project within a private git repo.

**Comment by justinwilaby** [comment]
https://github.com/jspm/jspm-cli/blob/master/lib/package.js#L297 appends the registry (`myGit`) to the dependencies which seems to be the root cause of the failure.

**Comment by subesokun** [comment]
Hi @justinwilaby, which version of jspm-git are you using? This issue is certainly a tricky one. If no registry is given in the dependencies then jspm will fallback to the registry that has been used to install the parent package. In the jspm-github registry some transformations are getting applied ([see here](https://github.com/jspm/github/blob/0.17/github.js#L499)), but I think that won't solve also your issue as you want to use the NPM registry and not the JSPM one. Generally it would be interesting to see how such registry switch to NPM could be detected and applied.

Is the package you're trying to install a NPM package or a JSPM package? If it's a JSPM package a workaround would be to explicitly define the registry for your NPM dependencies i.e. `"rollup-plugin-babel": "npm:rollup-plugin-babel"`. If it's a pure NPM package you'd need to install it via the NPM registry thought you'd need to publish your package in a private NPM registry in order to install it. If that is not possible and the NPM package is under your control then you could add also a `jspm` section to your `package.json` to define there the JSPM dependencies, [see here](https://github.com/jspm/jspm-cli/blob/0.17/docs/publishing-packages.md#publishing-jspm-style-packages-to-npm).

Does this help?
