### ISSUE TITLE
Cannot read length of null after upgrading to Git 2.10.0

### ISSUE THREAD

**Issue by davinkevin** [Orbs/jspm-git#50]
Hi, 

It seems after upgrading to the current last version of git, the module stop working. It returns an error `can not read length of null` generated by the line 88 of git.js

After analysis, it seems the regex parses only one digit for each part of the version number. 
So, the regex currently `/\d.\d.\d/` should take into account Major, minor or patch version upper to 10. To do that, something like `/\d+.\d+.\d+/` should do the job.

I will do PR to fix that.

Could it be integrated in the 0.4.X version ?

/cc @aubm

Thanks

**Comment by subesokun** [comment]
As mentioned in your PR I'll draft a new release this WE for the beta and the 0.4.x version.

**Comment by subesokun** [comment]
I've drafted now a new release. Due to some NPM publish mistake with the beta version your bug fixes are now available in the v0.6.0 release (will be installed with a `npm install jspm-git`). The new beta releases will be now v0.7.0-beta.x  (will be installed with a `npm install jspm-git@beta`).

Both the stable and beta version contains your fixes.
